### ISSUE TITLE
go yaml v3 is out

### ISSUE THREAD

**Issue by miekg** [miekg/yamlfmt#1]
yaml v3 keeps track of comment, which will make yamlfmt just perfect.

Move to yaml v3 .

**Comment by miekg** [comment]
latest masters supports this.

**Comment by daenney** [comment]
go-yaml v3 can't unmarshal its own output: https://github.com/go-yaml/yaml/issues/457. If you use `yamlfmt` now on a YAML file and then try to load it with go-yaml v3 it will break.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/yamlfmt] go yaml v3 is o..." ]
>go-yaml v3 can't unmarshal its own output: https://github.com/go-yaml/yaml/issues/457. If you use `yamlfmt` now on a YAML file and then try to load it with go-yaml v3 it will break.

lol, let see when that issue is fixed.

Thanks for the ping.

**Comment by niemeyer** [comment]
Should be fixed now. Please let me know if you see any other issues there.
